//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 10:22:34 PM CEST 
//


package pl.parser.nbp.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter2
    extends XmlAdapter<String, BigDecimal>
{


    public BigDecimal unmarshal(String value) {
        return (pl.parser.nbp.xml.BigDecimalParser.parseBigDecimal(value));
    }

    public String marshal(BigDecimal value) {
        return (pl.parser.nbp.xml.BigDecimalParser.printBigDecimal(value));
    }

}
